### ISSUE TITLE
[Feature request]: Add Async/Promises/CallbackFn

### ISSUE THREAD

**Issue by annymosse** [jeremyben/tsc-prog#4]
Add Async/Promises/CallbackFn to use in real cases, current state isn't differ than `tsc` cli.

**Comment by jeremyben** [comment]
This is intented for compilation scripts, not a web server. The typescript compiler is itself synchronous, so why bother wrapping it in an promise and then having to deal with asynchronous problems.

**Comment by annymosse** [comment]
actually you're right :)
